from __future__ import annotations

import json
import uuid
import zipfile
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import pandas as pd

from .clinical_dashboard import compile_clinical_dashboard_spec, compare_live_sql_and_cbp_paths
from .compiler import compile_dataframe
from .dashboard_equivalence import compare_dashboard_result_files, latency_comparison
from .models import ACBPCompilerOptions


def _now_utc() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _slug(value: str) -> str:
    cleaned = "".join(ch if ch.isalnum() else "_" for ch in str(value).strip())
    cleaned = "_".join(part for part in cleaned.split("_") if part)
    return cleaned[:60] or "acbp_project"


def _json_safe(obj: Any) -> Any:
    if isinstance(obj, dict):
        return {str(k): _json_safe(v) for k, v in obj.items()}

    if isinstance(obj, list):
        return [_json_safe(x) for x in obj]

    if hasattr(obj, "item"):
        try:
            return obj.item()
        except Exception:
            pass

    return obj


@dataclass
class ACBPCompilerProductService:
    product_home: str | Path

    def __post_init__(self) -> None:
        self.product_home = Path(self.product_home)
        self.product_home.mkdir(parents=True, exist_ok=True)

    def save_artifact_pack(
        self,
        kind: str,
        title: str,
        payload: dict[str, Any],
    ) -> dict[str, str]:
        project_id = f"{datetime.now().strftime('%Y%m%d_%H%M%S')}_{_slug(title)}_{uuid.uuid4().hex[:8]}"
        project_dir = self.product_home / project_id
        project_dir.mkdir(parents=True, exist_ok=True)

        manifest = {
            "project_id": project_id,
            "kind": kind,
            "title": title,
            "created_at": _now_utc(),
            "product": "ACBP Compiler",
            "artifact_type": "declared_truth_compiler_pack",
        }

        summary = payload.get("summary", payload)
        brief = payload.get("brief", "")

        (project_dir / "manifest.json").write_text(
            json.dumps(_json_safe(manifest), indent=2, ensure_ascii=False),
            encoding="utf-8",
        )

        (project_dir / "summary.json").write_text(
            json.dumps(_json_safe(summary), indent=2, ensure_ascii=False),
            encoding="utf-8",
        )

        (project_dir / "artifact.json").write_text(
            json.dumps(_json_safe(payload), indent=2, ensure_ascii=False),
            encoding="utf-8",
        )

        (project_dir / "deterministic_brief.md").write_text(
            brief or "# ACBP Compiler Artifact\n\nNo deterministic brief supplied.",
            encoding="utf-8",
        )

        readme = f"""# ACBP Compiler Artifact Pack

Project ID: `{project_id}`
Kind: `{kind}`
Created: `{manifest["created_at"]}`

## Contents

- `manifest.json`
- `summary.json`
- `artifact.json`
- `deterministic_brief.md`

## Guardrails

Declared valid count is not prediction correctness.
Derived invalid count is not model error.
Truth space is not the confusion matrix.

Generated by ACBP Compiler.
"""

        (project_dir / "README.md").write_text(readme, encoding="utf-8")

        return {
            "project_id": project_id,
            "project_url": f"/v1/projects/{project_id}",
            "export_url": f"/v1/projects/{project_id}/export",
        }

    def compile_clinical_dashboard(self) -> dict[str, Any]:
        artifact = compile_clinical_dashboard_spec()

        payload = {
            "summary": _json_safe(artifact.summary()),
            "brief": artifact.deterministic_brief(),
        }

        payload.update(
            self.save_artifact_pack(
                kind="clinical_dashboard_spec",
                title=artifact.spec_name,
                payload=payload,
            )
        )

        return payload

    def compare_clinical_dashboard_paths(self) -> dict[str, Any]:
        payload = _json_safe(compare_live_sql_and_cbp_paths())

        payload.update(
            self.save_artifact_pack(
                kind="live_sql_vs_cbp_path_comparison",
                title="clinical_dashboard_live_sql_vs_cbp_paths",
                payload=payload,
            )
        )

        return payload

    def compile_dataset_file(
        self,
        path: str | Path,
        original_name: str,
        target_col: str,
        risk_class: str | None = None,
        features: list[str] | None = None,
        options: ACBPCompilerOptions | None = None,
    ) -> dict[str, Any]:
        path = Path(path)
        suffix = path.suffix.lower()

        if suffix == ".csv":
            df = pd.read_csv(path)
        elif suffix in {".xlsx", ".xls"}:
            df = pd.read_excel(path)
        else:
            raise ValueError(f"Unsupported dataset file type: {suffix}")

        artifact = compile_dataframe(
            df=df,
            target_col=target_col,
            features=features,
            risk_class=risk_class,
            name=Path(original_name or path.name).stem,
            options=options or ACBPCompilerOptions(auto_compact=True),
        )

        payload = {
            "summary": _json_safe(artifact.summary()),
            "brief": artifact.deterministic_brief(),
        }

        payload.update(
            self.save_artifact_pack(
                kind="compiled_dataset",
                title=Path(original_name or path.name).stem,
                payload=payload,
            )
        )

        return payload

    def compare_dashboard_files(
        self,
        live_path: str | Path,
        cbp_path: str | Path,
        key_cols: list[str] | None = None,
        ignore_cols: list[str] | None = None,
        tolerance: float = 0.000001,
        live_ms: float | None = None,
        cbp_ms: float | None = None,
    ) -> dict[str, Any]:
        result = compare_dashboard_result_files(
            live_path=live_path,
            cbp_path=cbp_path,
            key_cols=key_cols or [],
            ignore_cols=ignore_cols or [],
            tolerance=tolerance,
        )

        if live_ms is not None and cbp_ms is not None:
            result["latency"] = latency_comparison(float(live_ms), float(cbp_ms))

        payload = {
            "summary": _json_safe(result),
            "brief": (
                "ACBP Dashboard Equivalence Report\n\n"
                "Live SQL and CBP dashboard exports were compared using normalized deterministic result hashes, "
                "row/column checks, and numeric tolerance."
            ),
        }

        payload.update(
            self.save_artifact_pack(
                kind="dashboard_equivalence_report",
                title="live_sql_vs_cbp_result_comparison",
                payload=payload,
            )
        )

        return payload

    def list_projects(self) -> list[dict[str, Any]]:
        rows = []

        for folder in sorted(self.product_home.iterdir(), reverse=True):
            if not folder.is_dir():
                continue

            manifest_path = folder / "manifest.json"

            if not manifest_path.exists():
                continue

            try:
                rows.append(json.loads(manifest_path.read_text(encoding="utf-8")))
            except Exception:
                continue

        return rows

    def get_project(self, project_id: str) -> dict[str, Any]:
        artifact_path = self.product_home / project_id / "artifact.json"

        if not artifact_path.exists():
            raise FileNotFoundError(project_id)

        return json.loads(artifact_path.read_text(encoding="utf-8"))

    def export_project_zip(self, project_id: str) -> Path:
        project_dir = self.product_home / project_id

        if not project_dir.exists():
            raise FileNotFoundError(project_id)

        zip_path = self.product_home / f"{project_id}.zip"

        if zip_path.exists():
            zip_path.unlink()

        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as z:
            for file in project_dir.rglob("*"):
                if file.is_file():
                    z.write(file, arcname=file.relative_to(project_dir))

        return zip_path


